substitutions:
  _REGION: asia-northeast1
  _ARTIFACT_REGISTRY: curio

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/curio-interest-vector:latest'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/curio-interest-vector:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/curio-interest-vector:latest'
      - '-f'
      - 'apps/jobs/interest-vector.Dockerfile'
      - 'apps'

  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/curio-interest-vector']
    waitFor: ['build']

  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -e 's|\$${IMAGE}|${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/curio-interest-vector:${SHORT_SHA}|g' \
            -e 's|\$${PROJECT_ID}|${PROJECT_ID}|g' \
          infra/cloudrun/curio-interest-vector.yaml | gcloud run jobs replace - --region=${_REGION}
    waitFor: ['push']

timeout: 600s
