apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: curio-db-migrate
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: team-aizawa:asia-northeast1:curio-prod
        run.googleapis.com/network-interfaces: '[{"network":"curio","subnetwork":"curio01"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      taskCount: 1
      template:
        spec:
          maxRetries: 3
          timeoutSeconds: 300
          serviceAccountName: 386684379642-compute@developer.gserviceaccount.com
          containers:
            - image: ${IMAGE}
              resources:
                limits:
                  memory: 512Mi
                  cpu: "1"
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: curio-database-url
                      key: latest
