apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: curio-admin
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/iap-enabled: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: team-aizawa:asia-northeast1:curio-prod
        run.googleapis.com/network-interfaces: '[{"network":"curio","subnetwork":"curio01"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 386684379642-compute@developer.gserviceaccount.com
      containers:
        - image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: curio-database-url
                  key: latest
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: CURIO_ADMIN_SESSION_SECRET
                  key: latest
  traffic:
    - percent: 100
      latestRevision: true
