apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: curio-api
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: team-aizawa:asia-northeast1:curio-prod
        run.googleapis.com/network-interfaces: '[{"network":"curio","subnetwork":"curio01"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 386684379642-compute@developer.gserviceaccount.com
      containers:
        - image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: NODE_ENV
              value: production
            - name: BETTER_AUTH_URL
              value: https://api.curio.axelaspor2.dev
            - name: CORS_ORIGINS
              value: https://app.curio.axelaspor2.dev
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: curio-database-url
                  key: latest
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: curio-auth-secret
                  key: latest
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: curio-google-client-id
                  key: latest
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: curio-google-client-secret
                  key: latest
  traffic:
    - percent: 100
      latestRevision: true
