# Terraform Apply Pipeline (Generic)
# Trigger: Push to main branch
# https://cloud.google.com/build/docs/build-config-file-schema

substitutions:
  _TF_VERSION: "1.14"

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true

steps:
  - id: "terraform-fmt"
    name: "hashicorp/terraform:${_TF_VERSION}"
    dir: "${_TF_DIR}"
    entrypoint: "terraform"
    args: ["fmt", "-check", "-recursive"]

  - id: "terraform-init"
    name: "hashicorp/terraform:${_TF_VERSION}"
    dir: "${_TF_DIR}"
    entrypoint: "terraform"
    args: ["init", "-input=false"]
    waitFor: ["terraform-fmt"]

  - id: "terraform-validate"
    name: "hashicorp/terraform:${_TF_VERSION}"
    dir: "${_TF_DIR}"
    entrypoint: "terraform"
    args: ["validate", "-no-color"]
    waitFor: ["terraform-init"]

  - id: "terraform-plan"
    name: "hashicorp/terraform:${_TF_VERSION}"
    dir: "${_TF_DIR}"
    entrypoint: "terraform"
    args: ["plan", "-no-color", "-lock=false", "-input=false", "-out=tfplan"]
    waitFor: ["terraform-validate"]

  - id: "terraform-apply"
    name: "hashicorp/terraform:${_TF_VERSION}"
    dir: "${_TF_DIR}"
    entrypoint: "terraform"
    args: ["apply", "-auto-approve", "-input=false", "tfplan"]
    waitFor: ["terraform-plan"]

timeout: "1200s"
